#!/bin/bash
#
# cmpunlocker - install the kernel-update persistence layer.
#
# Called by install.sh. Puts everything needed to rebuild the patched modules
# in system locations, so a kernel update rebuilds them automatically and the
# machine never silently falls back to the stock 8 GB driver or to nouveau.
#
# What lands where:
#   /var/lib/cmpunlocker/driver/     build payload (sources, patches, tarball)
#   /etc/cmpunlocker/build.conf      the compile-time flags to reproduce
#   /usr/lib/cmpunlocker/*.sh        rebuild / boot-check / pin helpers
#   /etc/kernel/... or pacman hook   rebuild trigger on kernel update
#   cmpunlocker-rebuild.service      boot-time safety net
#   /etc/depmod.d/cmpunlocker.conf   patched modules outrank the stock ones
#   /etc/modprobe.d/cmpunlocker.conf nouveau stays blacklisted
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

PAYLOAD_DIR="/var/lib/cmpunlocker"
CONF_DIR="/etc/cmpunlocker"
LIB_DIR="/usr/lib/cmpunlocker"

PIN_PACKAGES="${CMPUNLOCKER_PIN_PACKAGES:-1}"

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
    GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
else
    GREEN=""; YELLOW=""; CYAN=""; NC=""
fi
info() { echo -e "${CYAN}==>${NC} $*"; }
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }

[[ "${EUID}" -eq 0 ]] || { echo "must run as root" >&2; exit 1; }

# ------------------------------------------------------------------ payload --
#
# A copy of driver/ rather than a symlink into the user's clone: kernel updates
# have to keep working after the clone is moved, renamed or deleted.
#
info "Installing rebuild payload to ${PAYLOAD_DIR}..."
mkdir -p "${PAYLOAD_DIR}/driver" "${PAYLOAD_DIR}/state"
rm -rf "${PAYLOAD_DIR}/driver/patches" "${PAYLOAD_DIR}/driver/src"
cp -a "${REPO_DIR}/driver/build.sh" "${PAYLOAD_DIR}/driver/build.sh"
cp -a "${REPO_DIR}/driver/VERSION"  "${PAYLOAD_DIR}/driver/VERSION"
cp -a "${REPO_DIR}/driver/patches"  "${PAYLOAD_DIR}/driver/patches"
cp -a "${REPO_DIR}/driver/src"      "${PAYLOAD_DIR}/driver/src"
chmod +x "${PAYLOAD_DIR}/driver/build.sh"

#
# Carry the downloaded tarball over too. Without it every kernel update needs
# network access to GitHub, which a rig behind a flaky link may not have.
# Only the tarball, not the extracted tree - that is ~1 GB of rebuildable data.
#
mkdir -p "${PAYLOAD_DIR}/driver/.build"
shopt -s nullglob
for tarball in "${REPO_DIR}/driver/.build"/*.tar.gz; do
    cp -a "${tarball}" "${PAYLOAD_DIR}/driver/.build/"
done
shopt -u nullglob
if compgen -G "${PAYLOAD_DIR}/driver/.build/*.tar.gz" > /dev/null; then
    ok "Payload installed (source tarball cached — rebuilds work offline)"
else
    warn "No cached source tarball — kernel-update rebuilds will need network"
fi

# -------------------------------------------------------------- build.conf --
#
# The flags are compile-time, so a rebuild that does not replay them produces a
# driver without the user's overclock. Persisting them is what makes an
# automatic rebuild equivalent to re-running install.sh by hand.
#
info "Recording build configuration..."
mkdir -p "${CONF_DIR}"
cat > "${CONF_DIR}/build.conf" <<EOF
# Generated by cmpunlocker install.sh — do not edit by hand.
# Re-run install.sh to change these; kernel-update rebuilds replay them as-is.
CMPUNLOCKER_DRIVER_VERSION="${CMPUNLOCKER_DRIVER_VERSION:-}"
CMPUNLOCKER_MCLK_NDIV="${CMPUNLOCKER_MCLK_NDIV:-}"
CMPUNLOCKER_MCLK_TIMINGS="${CMPUNLOCKER_MCLK_TIMINGS:-}"
CMPUNLOCKER_ENABLE_P2P="${CMPUNLOCKER_ENABLE_P2P:-}"
EOF
chmod 0644 "${CONF_DIR}/build.conf"
ok "Saved ${CONF_DIR}/build.conf"

# ------------------------------------------------------------------ helpers --
info "Installing helper scripts to ${LIB_DIR}..."
mkdir -p "${LIB_DIR}"
install -m 0755 "${SCRIPT_DIR}/rebuild.sh"            "${LIB_DIR}/rebuild.sh"
install -m 0755 "${SCRIPT_DIR}/boot-check.sh"         "${LIB_DIR}/boot-check.sh"
install -m 0755 "${SCRIPT_DIR}/pin-packages.sh"       "${LIB_DIR}/pin-packages.sh"
install -m 0755 "${SCRIPT_DIR}/hooks/pacman-trigger.sh" "${LIB_DIR}/pacman-trigger.sh"
ok "Helper scripts installed"

# -------------------------------------------------------------------- hooks --
#
# One hook family per system. Picking by package manager rather than by which
# directories happen to exist avoids installing two hooks on a machine that has
# both, which would rebuild the same kernel twice.
#
info "Installing kernel-update hook..."
HOOK_KIND="none"
if command -v apt-mark &>/dev/null && [[ -d /etc/kernel/postinst.d ]]; then
    install -m 0755 "${SCRIPT_DIR}/hooks/kernel-postinst.sh" /etc/kernel/postinst.d/cmpunlocker
    mkdir -p /etc/kernel/postrm.d
    install -m 0755 "${SCRIPT_DIR}/hooks/kernel-postrm.sh"   /etc/kernel/postrm.d/cmpunlocker
    HOOK_KIND="debian"
    ok "Installed /etc/kernel/postinst.d/cmpunlocker (Debian/Ubuntu/HiveOS)"
elif command -v pacman &>/dev/null; then
    mkdir -p /etc/pacman.d/hooks
    install -m 0644 "${SCRIPT_DIR}/hooks/pacman.hook" /etc/pacman.d/hooks/95-cmpunlocker.hook
    HOOK_KIND="arch"
    ok "Installed /etc/pacman.d/hooks/95-cmpunlocker.hook (Arch)"
elif [[ -d /etc/kernel/install.d ]] || command -v kernel-install &>/dev/null; then
    mkdir -p /etc/kernel/install.d
    install -m 0755 "${SCRIPT_DIR}/hooks/kernel-install.sh" /etc/kernel/install.d/95-cmpunlocker.install
    HOOK_KIND="kernel-install"
    ok "Installed /etc/kernel/install.d/95-cmpunlocker.install (Fedora/RHEL)"
fi

if [[ "${HOOK_KIND}" == "none" ]]; then
    warn "No supported kernel hook directory found"
    warn "The boot-time service still rebuilds after a kernel update,"
    warn "it just costs one slow boot instead of rebuilding beforehand."
fi

# ------------------------------------------------------------------ service --
#
# The safety net for everything the hooks cannot see: hand-built kernels,
# restored snapshots, a hook that ran before the headers were unpacked.
#
if command -v systemctl &>/dev/null && [[ -d /etc/systemd/system ]]; then
    info "Installing boot-time safety net..."
    install -m 0644 "${SCRIPT_DIR}/cmpunlocker-rebuild.service" \
        /etc/systemd/system/cmpunlocker-rebuild.service
    systemctl daemon-reload 2>/dev/null || true
    systemctl enable cmpunlocker-rebuild.service >/dev/null 2>&1 || true
    ok "cmpunlocker-rebuild.service enabled"
else
    warn "systemd not found — no boot-time safety net installed"
fi

# ------------------------------------------------------------------- depmod --
info "Setting module resolution priority..."
mkdir -p /etc/depmod.d
install -m 0644 "${SCRIPT_DIR}/depmod-cmpunlocker.conf" /etc/depmod.d/cmpunlocker.conf
depmod -a 2>/dev/null || true
ok "Patched modules now outrank the stock driver in depmod"

# ----------------------------------------------------------------- nouveau --
info "Blocking the nouveau fallback..."
mkdir -p /etc/modprobe.d
install -m 0644 "${SCRIPT_DIR}/modprobe-cmpunlocker.conf" /etc/modprobe.d/cmpunlocker.conf

#
# This unit exists to load nouveau when nvidia fails to come up. On a CMP that
# turns a fixable driver problem into a card bound to a driver that cannot use
# it, so it is masked rather than left to fire.
#
if command -v systemctl &>/dev/null && \
   systemctl list-unit-files nvidia-fallback.service 2>/dev/null | grep -q nvidia-fallback; then
    systemctl mask nvidia-fallback.service >/dev/null 2>&1 || true
    ok "Masked nvidia-fallback.service (no automatic switch to nouveau)"
else
    ok "nouveau blacklisted (no nvidia-fallback.service on this system)"
fi

# --------------------------------------------------------------------- pin --
if [[ "${PIN_PACKAGES}" == "1" ]]; then
    info "Pinning NVIDIA package version..."
    #
    # Recorded rather than assumed: pinning depends on a plugin being present
    # and on repo metadata being reachable, so the installer summary has to
    # report what actually happened instead of what was asked for.
    #
    if "${LIB_DIR}/pin-packages.sh" pin; then
        echo "ok" > "${PAYLOAD_DIR}/state/pin-status"
    else
        echo "failed" > "${PAYLOAD_DIR}/state/pin-status"
        warn "NVIDIA packages are NOT pinned — a driver upgrade can break rebuilds"
        warn "Fix the cause above, then: sudo ${LIB_DIR}/pin-packages.sh pin"
    fi
else
    echo "skipped" > "${PAYLOAD_DIR}/state/pin-status"
    info "NVIDIA packages not pinned (--no-pin)"
    warn "A driver upgrade past $(tr '\n' ' ' < "${REPO_DIR}/driver/VERSION" 2>/dev/null || echo 'the supported versions')"
    warn "will make kernel-update rebuilds fail."
fi

echo ""
ok "Kernel-update persistence installed"
echo ""
